name: CI-CD para NextJS

on:
  push:
      branches: [master]
    pull_request:
      branches: [master]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm run install
      - name: Lint
        run: npm run lint