name: CI-CD para NextJS

on:
  
 
push:
    
   
branches: [master]
  pull_request:
    branches: [master]

jobs:
  lint:
    
   
name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Lint
        
       
run: npm run lint